In [14]:
import pandas as pd
import numpy as np
test = pd.read_csv("/home/sunshuo/qml/TradeMaster_reframe/experiment_result/data/test.csv",index_col=0)
test

,date,open,high,low,close,adjcp,tic,zopen,zhigh,zlow,zadjcp,zclose,zd_5,zd_10,zd_15,zd_20,zd_25,zd_30
0,2021-01-04,133.520004,133.610001,126.760002,129.410004,128.453430,AAPL,0.031760,0.032455,-0.020478,-0.007392,-0.024719,0.031420,0.017758,0.002323,-0.010486,-0.021578,-0.034987
0,2021-01-04,231.250000,231.250000,223.669998,226.660004,217.989258,AMGN,0.020251,0.020251,-0.013192,-0.038254,-0.014179,0.000856,-0.004266,0.001206,0.002958,0.000972,-0.002494
0,2021-01-04,121.300003,121.800003,116.849998,118.040001,116.058220,AXP,0.027618,0.031854,-0.010081,-0.016789,-0.023737,0.007930,-0.002330,0.000971,0.011670,0.014202,0.010022
0,2021-01-04,210.000000,210.199997,202.490005,202.720001,202.720001,BA,0.035912,0.036898,-0.001135,0.000000,-0.052976,0.051490,0.065741,0.083935,0.102499,0.099298,0.089213
0,2021-01-04,183.000000,185.979996,180.250000,182.149994,176.713684,CAT,0.004667,0.021027,-0.010431,-0.029845,0.000714,-0.012649,-0.014598,-0.014490,-0.014181,-0.020199,-0.024026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,2021-12-31,504.140015,506.869995,502.040009,502.140015,500.658447,UNH,0.003983,0.009420,-0.000199,-0.002951,-0.004540,0.001549,-0.011798,-0.019499,-0.033978,-0.050399,-0.061491
251,2021-12-31,216.809998,217.979996,215.490005,216.710007,216.358002,V,0.000461,0.005860,-0.005630,-0.001624,-0.005324,0.004504,-0.003733,-0.009401,-0.020156,-0.035947,-0.042575
251,2021-12-31,52.200001,52.310001,51.880001,51.959999,50.723785,VZ,0.004619,0.006736,-0.001540,-0.023792,-0.005550,0.008353,0.013203,0.001899,-0.004224,-0.007667,-0.008154
251,2021-12-31,51.900002,52.419998,51.830002,52.160000,51.639271,WBA,-0.004985,0.004985,-0.006327,-0.009983,0.003270,-0.008589,-0.027818,-0.036337,-0.046492,-0.064555,-0.069562
251,2021-12-31,143.199997,145.039993,142.919998,144.690002,144.132538,WMT,-0.010298,0.002419,-0.012233,-0.003853,0.010617,-0.012910,-0.024832,-0.018767,-0.026154,-0.027970,-0.024153

In [15]:
technical_indicator=["zopen","zhigh", "zlow", "zadjcp", "zclose", "zd_5", "zd_10","zd_15", "zd_20", "zd_25", "zd_30"]

In [16]:
all_dataframe_list=[]
for i in range(test.index.unique()[-1]+1):
    information=test[test.index==i]
    new_dataframe=[]
    for tech in technical_indicator:
        tech_value=np.mean(information[tech])
        new_dataframe.append(tech_value)
    all_dataframe_list.append(new_dataframe)
new_df = pd.DataFrame(all_dataframe_list,columns=technical_indicator)    
        
new_df

,zopen,zhigh,zlow,zadjcp,zclose,zd_5,zd_10,zd_15,zd_20,zd_25,zd_30
0,0.013520,0.018903,-0.013110,-0.027754,-0.011270,0.004675,0.000585,0.000279,0.000450,-0.002112,-0.005572
1,-0.006775,0.008240,-0.013609,-0.027515,0.005160,-0.000444,-0.004146,-0.004629,-0.004932,-0.006716,-0.009717
2,-0.011904,0.011872,-0.018804,-0.027515,0.013477,-0.010081,-0.014673,-0.015372,-0.016496,-0.017649,-0.020363
3,-0.003480,0.010242,-0.013406,-0.027051,0.007501,-0.013490,-0.018801,-0.021310,-0.022769,-0.023511,-0.026068
4,0.000732,0.007880,-0.011980,-0.027051,0.001537,-0.011841,-0.017192,-0.021052,-0.022886,-0.023559,-0.026377
...,...,...,...,...,...,...,...,...,...,...,...
247,-0.007728,0.001423,-0.012106,-0.006839,0.009124,-0.015619,-0.017214,-0.018874,-0.027442,-0.027153,-0.024358
248,-0.003216,0.006696,-0.006475,-0.006839,0.002975,-0.010951,-0.017661,-0.019341,-0.028186,-0.028834,-0.026843
249,-0.001928,0.005166,-0.006219,-0.006839,0.002305,-0.008139,-0.017087,-0.019778,-0.027284,-0.029861,-0.028596
250,0.004097,0.009604,-0.001814,-0.006839,-0.002240,-0.002522,-0.013206,-0.016015,-0.021563,-0.026838,-0.026101
251,0.001025,0.007252,-0.003795,-0.006839,-0.001552,0.001136,-0.010333,-0.012979,-0.017388,-0.024479,-0.024071

In [17]:
information=test[test.index==0]

In [18]:
np.mean(information["open"])

158.51826950599408